import { PALETTE } from "./palette";

export const PAPER_THEME = {
  colors: {
    primary: PALETTE.bluePrimary,
    onPrimary: PALETTE.blueSecondary,
    primaryContainer: PALETTE.bluePrimary,
    onPrimaryContainer: PALETTE.bluePrimary,
    secondary: PALETTE.bluePrimary,
    onSecondary: PALETTE.bluePrimary,
    secondaryContainer: PALETTE.bluePrimary,
    onSecondaryContainer: PALETTE.bluePrimary,
    tertiary: "rgb(243, 183, 190)",
    onTertiary: "rgb(75, 37, 43)",
    tertiaryContainer: "rgb(101, 58, 65)",
    onTertiaryContainer: "rgb(255, 217, 221)",
    error: PALETTE.error,
    onError: PALETTE.error,
    errorContainer: PALETTE.bluePrimary,
    onErrorContainer: PALETTE.bluePrimary,
    background: PALETTE.bluePrimary,
    onBackground: PALETTE.bluePrimary,
    surface: PALETTE.bluePrimary,
    onSurface: PALETTE.bluePrimary,
    surfaceVariant: PALETTE.blueSecondary,
    onSurfaceVariant: PALETTE.textPrimary,
    outline: PALETTE.bluePrimary,
    outlineVariant: PALETTE.bluePrimary,
    shadow: PALETTE.bluePrimary,
    scrim: PALETTE.bluePrimary,
    inverseSurface: PALETTE.bluePrimary,
    inverseOnSurface: PALETTE.bluePrimary,
    inversePrimary: PALETTE.bluePrimary,
    elevation: {
      level0: "transparent",
      level1: "rgb(39, 35, 41)",
      level2: "rgb(44, 40, 48)",
      level3: "rgb(50, 44, 55)",
      level4: "rgb(52, 46, 57)",
      level5: "rgb(56, 49, 62)",
    },
    surfaceDisabled: PALETTE.bluePrimary,
    onSurfaceDisabled: PALETTE.bluePrimary,
    backdrop: PALETTE.bluePrimary,
  },
};
